### ISSUE TITLE
Tapebuddy64: tape-gui.py doesnt show read data visualisation

### ISSUE THREAD

**Issue by InsaneDruid** [wagiminator/C64-Collection#21]
Tested with Python 3.12.5/tkinter 8.6 on Windows11 and Python 3.10.12/tkinter 8.6 on KDE NEON
After clicking read from tape to tap file and selecting the output file, only a blank window appears with no graphical output, 
**<EDIT: the tkinter error i also reported  was a fluke, but the missing graphical output remained>**
The tape gets read though and the produced tap files do work.

![Screenshot 2024-09-05 110220](https://github.com/user-attachments/assets/e07262f0-1efb-4194-873f-103dc6a5d1b8)

**Comment by InsaneDruid** [comment]
I don't pretent to be a python coder, but changing the contentWindow.update_idletasks() function calls in the tapeRead() function to contentWindow.update() ones solved the issue, now the window responds with "press play on tape" -> "searching" -> "reading from tape" and showing the read data, too!

**Comment by wagiminator** [comment]
Hi, thanks a lot for the information. I’m not a Python coder myself; I somehow taught myself the little bit I needed ;-) If it works now, feel free to submit a pull request. I assume that it will work for me as well with the change.

**Comment by wagiminator** [comment]
Already made the fix.

**Comment by InsaneDruid** [comment]
Oh cool. I was just experimenting with my one and discovered the same issue on the progress bar for writing, i see you fixed that too. Nice!

Thanks
