### ISSUE TITLE
USB-C to 1541-II Power Adapter L1 wrong Footprint

### ISSUE THREAD

**Issue by venice1200** [wagiminator/C64-Collection#7]
Hi,
at first, thank you for this cool and useful adapter and all the other tools in this Repo.

In have orderred a few boards and SMD components but L1 from the BOM doesn’t match the board if i’am correct.

![02BFF18A-0894-45B7-8187-1A96FA081369](https://user-images.githubusercontent.com/43762187/224749313-f019cd99-e69d-4fef-bdcb-4d84fbbae0e5.jpeg)

My L1 looks much smaller than yours.

Hopefully there is a matching part available.

Or is maybe the PSPMAA0805-4R7M-ANP the correct one?
It's the same you have used here: https://github.com/wagiminator/Power-Boards/blob/master/78xx_Replacement_SD8942/78xx_Replacement_BOM.tsv

**Comment by wagiminator** [comment]
Oh yes, you're right. I will correct the BOM

**Comment by venice1200** [comment]
Ok.
But with the „Big One“ there is not much Space in the Case.
Anyway, closed!
